class Iformacoes {
  final Map<int, String> _info = {
    1: "Riscos para a saúde: Ter um IMC abaixo de 18,5 pode indicar uma ingestão insuficiente de calorias e nutrientes essenciais. Estar abaixo do peso pode aumentar o risco de problemas de saúde, tais como: \n- Fragilidade óssea e maior risco de osteoporose. \n- Fraqueza muscular e redução da massa muscular. \n- Comprometimento do sistema imunológico e maior suscetibilidade a infecções. \n- Desequilíbrios hormonais. \n- Fadiga e falta de energia. \n- Problemas de fertilidade em mulheres. \n- Deficiências nutricionais, como deficiência de vitaminas e minerais.",
    2: "Você está com o peso ideal, parabéns! Manter um peso saudável é um grande feito.",
    3: "O sobrepeso pode aumentar o risco de várias condições de saúde, incluindo: \n- Doenças cardiovasculares, como hipertensão arterial, doença arterial coronariana e acidente vascular cerebral (AVC). \n- Diabetes tipo 2. \n- Distúrbios metabólicos, como resistência à insulina e síndrome metabólica. \n- Problemas articulares, como osteoartrite. \n- Distúrbios respiratórios, como apneia do sono. \n- Certos tipos de câncer, como câncer de mama, cólon e próstata. \n- Problemas de fertilidade. \n- Problemas de saúde mental, como baixa autoestima e depressão. \nLembre-se de que a perda de peso saudável envolve tempo e esforço. É importante ter uma abordagem equilibrada, buscando melhorar sua saúde geral, em vez de apenas focar no número da balança. Consultar um profissional de saúde qualificado irá ajudar você a desenvolver um plano adequado às suas necessidades específicas.",
    4: "Riscos para a saúde: A obesidade de grau 1, 2 e 3 estão associadas a um maior risco de várias condições de saúde, incluindo: \n- Doenças cardiovasculares, como doença arterial coronariana, hipertensão arterial e acidente vascular cerebral (AVC). \n- Diabetes tipo 2. \n- Distúrbios metabólicos, como resistência à insulina e síndrome metabólica. \n- Apneia do sono e problemas respiratórios. \n- Doenças articulares, como osteoartrite. \n- Certos tipos de câncer, como câncer de mama, cólon e próstata. \n- Problemas de saúde mental, como depressão e baixa autoestima. \n- Complicações na gravidez. \n- Problemas de fertilidade. \nLembre-se de que a perda de peso saudável envolve tempo e esforço. É importante ter uma abordagem equilibrada, buscando melhorar sua saúde geral, em vez de apenas focar no número da balança. Consultar um profissional de saúde qualificado irá ajudar você a desenvolver um plano adequado às suas necessidades específicas.",
  };

  Map get info => _info;
}
